/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.co.udea.mintic.navegacion.frames;

/**
 *
 * @author CarlosRomero
 */
public class FrameUno extends javax.swing.JFrame {

    /**
     * Creates new form FrameUno
     */
    public FrameUno() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotonesUno = new javax.swing.JPanel();
        btnIraTres = new javax.swing.JButton();
        btnIraDos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uno");

        btnIraTres.setText("Ir a Tres");
        btnIraTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraTresActionPerformed(evt);
            }
        });

        btnIraDos.setText("Ir a Dos");
        btnIraDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraDosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesUnoLayout = new javax.swing.GroupLayout(pnlBotonesUno);
        pnlBotonesUno.setLayout(pnlBotonesUnoLayout);
        pnlBotonesUnoLayout.setHorizontalGroup(
            pnlBotonesUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesUnoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnIraDos)
                .addGap(68, 68, 68)
                .addComponent(btnIraTres)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlBotonesUnoLayout.setVerticalGroup(
            pnlBotonesUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesUnoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlBotonesUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIraTres)
                    .addComponent(btnIraDos))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlBotonesUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(pnlBotonesUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIraDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraDosActionPerformed

        FrameDos frmDos = new FrameDos();
        this.setVisible(Boolean.FALSE);
        frmDos.setVisible(true);
    }//GEN-LAST:event_btnIraDosActionPerformed

    private void btnIraTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraTresActionPerformed
        FrameTres frmTres = new FrameTres();
        this.setVisible(Boolean.FALSE);
        frmTres.setVisible(true);
    }//GEN-LAST:event_btnIraTresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIraDos;
    private javax.swing.JButton btnIraTres;
    private javax.swing.JPanel pnlBotonesUno;
    // End of variables declaration//GEN-END:variables
}
