/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.co.udea.mintic.navegacion.frames;

/**
 *
 * @author CarlosRomero
 */
public class FrameDos extends javax.swing.JFrame {

    /**
     * Creates new form FrameDos
     */
    public FrameDos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotonesDos = new javax.swing.JPanel();
        btnIraUno = new javax.swing.JButton();
        btnIraTres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dos");

        btnIraUno.setText("Ir a Uno");
        btnIraUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraUnoActionPerformed(evt);
            }
        });

        btnIraTres.setText("Ir a Tres");
        btnIraTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraTresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesDosLayout = new javax.swing.GroupLayout(pnlBotonesDos);
        pnlBotonesDos.setLayout(pnlBotonesDosLayout);
        pnlBotonesDosLayout.setHorizontalGroup(
            pnlBotonesDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesDosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnIraUno)
                .addGap(62, 62, 62)
                .addComponent(btnIraTres)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlBotonesDosLayout.setVerticalGroup(
            pnlBotonesDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesDosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlBotonesDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIraUno)
                    .addComponent(btnIraTres))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlBotonesDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(pnlBotonesDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIraUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraUnoActionPerformed

        FrameUno frmUno = new FrameUno();
        this.setVisible(Boolean.FALSE);
        frmUno.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_btnIraUnoActionPerformed

    private void btnIraTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraTresActionPerformed
        FrameTres frmTres = new FrameTres();
        this.setVisible(Boolean.FALSE);
        frmTres.setVisible(true);
    }//GEN-LAST:event_btnIraTresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIraTres;
    private javax.swing.JButton btnIraUno;
    private javax.swing.JPanel pnlBotonesDos;
    // End of variables declaration//GEN-END:variables
}
