/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.co.udea.mintic.navegacion.paneles;

import com.co.udea.mintic.model.figura.Circulo;

/**
 *
 * @author CarlosRomero
 */
public class Figura extends javax.swing.JPanel {

    /**
     * Creates new form Figura
     */
    public Figura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaludoFigura = new javax.swing.JLabel();
        pnlCirculo = new javax.swing.JPanel();
        txtRadio = new javax.swing.JTextField();
        lblRadio = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblPerimetro = new javax.swing.JLabel();
        lblResultArea = new javax.swing.JLabel();
        lblResultPerimetro = new javax.swing.JLabel();
        btnProcesarCirculo = new javax.swing.JButton();
        lblMensajeLib = new javax.swing.JLabel();
        pnlCuadrado = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblSaludoFigura.setText("Hola desde figura");

        pnlCirculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Circulo"));

        lblRadio.setText("Radio");

        lblArea.setText("Area");

        lblPerimetro.setText("Perimetro");

        btnProcesarCirculo.setText("Calcular");
        btnProcesarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCirculoLayout = new javax.swing.GroupLayout(pnlCirculo);
        pnlCirculo.setLayout(pnlCirculoLayout);
        pnlCirculoLayout.setHorizontalGroup(
            pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCirculoLayout.createSequentialGroup()
                        .addComponent(lblPerimetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultPerimetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCirculoLayout.createSequentialGroup()
                        .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblResultArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProcesarCirculo)
                    .addComponent(lblMensajeLib, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlCirculoLayout.setVerticalGroup(
            pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCirculoLayout.createSequentialGroup()
                .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCirculoLayout.createSequentialGroup()
                        .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnProcesarCirculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCirculoLayout.createSequentialGroup()
                        .addGroup(pnlCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerimetro)
                            .addComponent(lblResultPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(lblMensajeLib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlCuadrado.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuadrado"));

        javax.swing.GroupLayout pnlCuadradoLayout = new javax.swing.GroupLayout(pnlCuadrado);
        pnlCuadrado.setLayout(pnlCuadradoLayout);
        pnlCuadradoLayout.setHorizontalGroup(
            pnlCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        pnlCuadradoLayout.setVerticalGroup(
            pnlCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblSaludoFigura))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(pnlCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSaludoFigura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarCirculoActionPerformed
        Double dato = Double.parseDouble(txtRadio.getText());
        Circulo objCir = new Circulo(dato);

        lblResultArea.setText(String.valueOf(objCir.calcularArea(null, null, dato)));
        lblResultPerimetro.setText(String.valueOf(objCir.calcularPerimetro(null, null, dato)));

        lblMensajeLib.setText(objCir.mensaje());
    }//GEN-LAST:event_btnProcesarCirculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesarCirculo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblMensajeLib;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JLabel lblResultArea;
    private javax.swing.JLabel lblResultPerimetro;
    private javax.swing.JLabel lblSaludoFigura;
    private javax.swing.JPanel pnlCirculo;
    private javax.swing.JPanel pnlCuadrado;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
